### ISSUE TITLE
Skip problem with PlexKodiConnect

### ISSUE THREAD

**Issue by explorerswb** [cjmanca/plex-credits-detect#28]
I set this up a few days ago as a docker container on my NAS, and once I got the configuration files sorted out it's been working its way through my library ever since. First, I want to say thanks, because it was a surprisingly simple process, and it's been working more or less exactly as expected. 

The problem I'm having is that one of my users uses PlexKodiConnect (https://github.com/croneter/PlexKodiConnect), and it seems that pressing the Skip Intro button during the intro credits will skip all the way to the end of the end credits.

It works flawlessly when using Plex web or Plex Windows. It seems to only be a problem with PlexKodiConnect. I can only assume that since PKC isn't meant to deal with multiple intro markers, it's just grabbing the endTimeOffset with the highest value. For the moment I've had them just disable Skip Intro entirely.

I realize that any fix for this would almost certainly have to be implemented in the PlexKodiConnect code, and I will be opening an issue over there as well, but I wanted to post it here on the off chance that there is some database magic that could resolve the problem on your end.

Thanks, and thanks again for all the work you've put into this!

**Comment by cjmanca** [comment]
I don't think there's anything I can do about that if it's working as you say. All PCD is doing is inserting extra intro markers into the plex intro table. I don't have any control over how clients handle those markers, although all the clients I've tested with have worked as expected.

As long as you've verified that the markers are correct for that same video on another client, and it's only that one client having the issue, then it would have to be fixed in that client.

**Comment by explorerswb** [comment]
Yeah, that's pretty much what I expected. And I've tested a few different videos using Windows, Android, Web, and PKC clients. They work perfectly with everything I've tested, except for PKC.

Thanks for the help!
